name: Compile and upload résumé PDF

on:
  push:
    branches:
      - "main"
    paths:
      - "resume.tex"
      - "index.html"
      - ".github/workflows/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "resume.tex"
      - "index.html"
      - ".github/workflows/**"

permissions:
  contents: write # Ensure sufficient permissions

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Post Processing
        run: |
          mkdir build 
          cp *.pdf build/ 
          cp index.html build/

      - name: Git add
        run: git add resume.pdf

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          git pull origin gh-pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          clean: true
